### ISSUE TITLE
Lines under the tabs when clicking on the geoblocker app 

### ISSUE THREAD

**Issue by andyxheli** [HomeITAdmin/nextcloud_geoblocker#64] opened 2021-04-12 14:37 UTC
@HomeITAdmin  Sorry to bother you but Can the lines be removed when clicking on the Geoblocker please see picture 

Before clicking on Geoblocker tab 
![image](https://user-images.githubusercontent.com/59488153/114412094-6485cf00-9b72-11eb-8ef0-7472882525e6.png)

After selecting the tab 
![image](https://user-images.githubusercontent.com/59488153/114412028-5afc6700-9b72-11eb-869d-52b95c382a4e.png)

**Comment by HomeITAdmin** [comment] 2021-04-14 16:12
Interesting... do not even know how I would reach this if I want to. :-)
But I can confirm, I have see in my Nextcloud too. I have to look into this.
Which NC Version are you using?

**Comment by andyxheli** [comment] 2021-04-14 16:29
@HomeITAdmin My live is on Nextcloud 20 and test is on Nextcloud 21 same on both 
Live Nextcloud 20.0.8
Test Nextcloud 21.0.1

**Comment by andyxheli** [comment] 2021-04-17 14:39
@HomeITAdmin so off topic but every time i enter the tab its always asking for a password anyway to go around that? but as far as this issue #65 should fix it i removed the code for text-decoration: underline clear browser cache issue fixed

**Comment by HomeITAdmin** [comment] 2021-04-17 14:53
Thanks a lot for finding the root cause.
For the solution I would go another way with limiting the effect of the css an the page only. This way all styling are still possible without effecting anything else. What do you think?
(For the other point it probably makes sense to open another issue. I am not experiencing this, neither on my test system nor on the productive systems. So we have to go into more details.)

**Comment by andyxheli** [comment] 2021-04-17 15:56
@HomeITAdmin You're very welcome! Your solution looks good to me :) Let do it. 

Hmm okay it wired but its not a big deal maybe beacse i closed my browser but my nextcloud session was still active so when i went back in and clicked on the geo tab then it asked me if i login into a new session on the web it will not ask me.

**Comment by HomeITAdmin** [comment] 2021-04-18 09:04
Ok, I close the issue then. Will come with the next release.

**Closed by HomeITAdmin** 2021-04-18 09:04 UTC
Labels: bug
